sudo: required

language: node_js

services:
  - docker

os:
  - osx
  - linux

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - python3-pip
    - python3.5
    - g++-7

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CC=gcc-7; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=g++-7; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start && sleep 3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export LDFLAGS="-L/usr/local/opt/openssl/lib"; fi
  - env
  - openssl version
  - ./scripts/travis-before-install

node_js:
  - 8

install:
  - npm install --verbose

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run start-test-server; else true; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm test; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm test-configure; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm test-electron; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm test-configure; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm test-electron; fi

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run coverage; else true; fi

notifications:
  email: false